DADOS_INVALIDOS = 'DADOS INVALIDOS'
DADOS_FALTANDO = 'DADOS FALTANDO'
ERRO_DE_PERMISSOES = 'ERRO DE PERMISSOES'
PERMISSAO_NEGADA = 'PERMISSOES NEGADAS'
NAO_AUTORIZADO = 'NAO AUTORIZADO'
CONSULTA_NAO_ENCONTRADA = "Consulta não encontrada"