# Generated by Django 4.2.3 on 2025-01-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, default='Nenhuma observação'),
            preserve_default=False,
        ),
    ]
